[package]
name = "expression_engine"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
hotpath = ["hotpath/hotpath"]
hotpath-alloc = ["hotpath/hotpath-alloc"]

[dependencies]
hotpath.workspace = true

datastore.workspace = true
keys.workspace = true
message.workspace = true
shareable_string.workspace = true
units.workspace = true

[lints]
workspace = true
