[package]
name = "built_in_registry"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
component_common.workspace = true
datastore.workspace = true
expression_engine.workspace = true
keys.workspace = true
message.workspace = true
phf.workspace = true

[build-dependencies]
camino.workspace = true
glob.workspace = true
phf_codegen.workspace = true

[lints]
workspace = true
